---
-
  hosts: test1

  tasks:
    -
      name: "change grub net.ifnames"
      lineinfile:
        path: /etc/default/grub
        regexp: '^net.ifnames'
        insertafter: 'net.ifnames=0 '
      notify: write_changes
    -
      name: "change grub net.ifnames"
      lineinfile:
        path: /etc/default/grub
        regexp: '^biosdevname'
        insertafter: 'biosdevname=0 '
      notify: write_changes
  
  handlers:
    - 
      name: write_changes
      shell:
        cmd: grub2-mkconfig