---
# handlers file for deploy_httpd

- name: restart httpd service
  systemd:
    daemon_reload: true
    state: restarted
    name: "{{ ansible_local.localfacts.localfacts.service }}"
    enabled: true
